### ISSUE TITLE
Preparación de la aplicación para su posterior internacionalización a la lengua castellana

### ISSUE THREAD

**Issue by fmm1005** [fmm1005/GESPRO_PracticaGestionTareas_2021#53]
- [ ] Investigación de las costumbres españolas para no generar polémica

- [ ] Tener en cuenta en la divisa Española que es diferente a la del pais origen Inglaterra (libras)

- [ ] Regulación de símbolos

- [ ] Se realizarán los cambios precisos para que la aplicación mejore la usabilidad de todos aquellas personas de lengua castellana

- [ ] Adaptar el calendario al formato Español

- [ ] Adaptar el diseño de la interfaz de acuerdo a región en la que estimamos que la aplicación va a tener un mayor éxito
